---@type vim.lsp.Config
return {
  cmd = { "typos-lsp" },
  filetypes = {
    "bash",
    "bicep",
    "c",
    "cpp",
    "css",
    "cs",
    "csproj",
    "dart",
    "dockerfile",
    "go",
    "graphql",
    "groovy",
    "html",
    "javascript",
    "javascriptreact",
    "json",
    "jsonc",
    "kotlin",
    "lua",
    "markdown",
    "nix",
    "ps1",
    "python",
    "rust",
    "scss",
    "sh",
    "sql",
    "terraform",
    "toml",
    "typescript",
    "typescriptreact",
    "yaml",
  },
  root_markers = { "typos.toml", "_typos.toml", ".typos.toml", "pyproject.toml", "Cargo.toml" },
  settings = {},
}
