require("configs.lsp").defaults()

local servers = {
  "ansiblels",
  "bashls",
  "bicep",
  "cmake",
  "cssls",
  "docker_language_server",
  "emmet_ls",
  "eslint",
  "gh_actions_ls",
  "gopls",
  "graphql",
  "harper_ls",
  "helm_ls",
  "html",
  "jinja_lsp",
  "jsonls",
  "kotlin_language_server",
  "lemminx",
  "lua_ls",
  "marksman",
  "nginx_language_server",
  "nil_ls",
  "powershell_es",
  "pyright",
  "rpmspec",
  "rust_analyzer",
  "sqlls",
  "systemd_lsp",
  "taplo",
  "terraformls",
  "tflint",
  "ts_ls",
  "typos_lsp",
  "vimls",
  "yamlls",
}

vim.lsp.enable(servers)
-- read :h vim.lsp.config for changing options of lsp servers
