gui:
  showIcons: true
  showFileIcons: true
  nerdFontsVersion: "3"
  splitDiff: false
  sidePanelWidth: 0.3
git:
  diffContextSize: 1000
  diffRenderers:
    - colorArg: always
      command: $HOME/.config/delta/lazygit-delta
