gui:
  showIcons: true
  showFileIcons: true
  nerdFontsVersion: "3"
  splitDiff: false
  sidePanelWidth: 0.3
git:
  diffContextSize: 1000
  paging:
    colorArg: always
    pager: delta --side-by-side --paging=never --line-numbers
