"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
[░▒▓](white)\
[$time$hostname](bg:white fg:black)\
[](bg:black fg:white)\
$username\
[](bg:blue fg:black)\
$directory\
[](fg:blue bg:bright-black)\
$git_branch\
$git_status\
[](fg:bright-black bg:black)\
$nodejs\
$rust\
$golang\
$php\
$dotnet\
$dart\
$lua\
$docker_context\
[](fg:black bg:bright-black)\
$battery\
[ ](fg:bright-black)\
\n$character"""

[directory]
style = "fg:black bg:blue"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = " "
"Videos" = "󰕧 "
"Projects" = "󰲋 "
"Workspace" = "󰖲 "
"Code" = "󰘦 "
"Repos" = "󰳏 "
"Git" = " "
"Config" = " "
".config" = " "
"Home" = " "
"Public" = " "
"Templates" = " "
"tmp" = " "
"Temp" = " "
"Cache" = "󰃨 "
".cache" = "󰃨 "
"Library" = "󰂺 "
"Applications" = "󰀻 "
"include" = " "
"src" = "󰴉 "
"node_modules" = " "
"venv" = "󰌠 "
".venv" = "󰌠 "
"env" = "󰌠 "
"docker" = " "
"kubernetes" = "󱃾 "
"Downloads_old" = " "
"Backup" = "󰁯 "
"Backups" = "󰁯 "
"Notes" = "󱞁 "
"Obsidian" = "󱞁 "

[git_branch]
symbol = ""
style = "bg:bright-black"
format = '[[ $symbol $branch ](fg:blue bg:bright-black)]($style)'

[git_status]
style = "bg:bright-black"
format = '[[($all_status$ahead_behind )](fg:blue bg:bright-black)]($style)'

[dotnet]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[dart]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[nodejs]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[rust]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[golang]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[docker_context]
symbol = " "
style = "bg:black"
format = '[[ $symbol $context ](fg:blue bg:black)]($style)'
only_with_files = true

[lua]
symbol = ""
style = "bg:black"
format = '[[ $symbol ($version) ](fg:blue bg:black)]($style)'

[azure]
disabled = false
symbol = "󰠅 "
style = "bg:black"
format = '[[ $symbol $subscription ](fg:blue bg:black)]($style)'

[os]
disabled = false
style = "fg:black bg:white"

[os.symbols]
Windows = " "
Linux = " "
Fedora = ""
Macos = " "

[battery]
disabled = false

[username]
style_user = "fg:blue bg:black"
style_root = "fg:red bg:black"
format = '[[ 󰀄 $user](fg:blue bg:black)]($style_user)'
show_always = true

[hostname]
style = "bg:white fg:black"
format = '[[ 󰟀 $hostname](fg:black bg:white)]($style)'
ssh_only = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bright-black"
format = '[[ $time](bg:white fg:black)]($style)'
