-- Upstream sets no `filetypes`, and a nil filetypes list means the server attaches to
-- *every* buffer. This restricts it to languages where the checks are worth having.
-- Inherited: cmd, root_markers, settings.
---@type vim.lsp.Config
return {
  filetypes = {
    "bash",
    "bicep",
    "c",
    "cpp",
    "css",
    "cs",
    "csproj",
    "dart",
    "dockerfile",
    "go",
    "graphql",
    "groovy",
    "html",
    "javascript",
    "javascriptreact",
    "json",
    "jsonc",
    "kotlin",
    "lua",
    "markdown",
    "nix",
    "ps1",
    "python",
    "rust",
    "scss",
    "sh",
    "sql",
    "terraform",
    "toml",
    "typescript",
    "typescriptreact",
    "yaml",
  },
}
